name: Windows Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        shell: cmd
        run: pyinstaller main.py --name AuterGUI --noconsole --windowed --icon ico.ico

      - name: Zip artifact
        shell: powershell
        run: Compress-Archive -Path dist/AuterGUI/* -DestinationPath AuterGUI-win.zip -Force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: AuterGUI-win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
